version: 2

defaults: &defaults
  working_directory: ~/rollup-plugin-just-gzip
  docker:
    - image: circleci/node:8

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - rollup-plugin-just-gzip-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - rollup-plugin-just-gzip-


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: rollup-plugin-just-gzip-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests and checks
          command: yarn test
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Creating bundles
          command: mkdir dist
      - run:
          name: Foo barring
          command: echo 'foo bar' > dist/foo.txt
      - store_artifacts:
        path: dist

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Adding NPM auth token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Releasing to GitHub & NPM
          command: ls -al ~/.npmrc

workflows:
  version: 2
  automated:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
            - test
      - publish:
          filters:
            branches:
              only:
                - master
          context: org-global
          requires:
            - install
            - test
            - build
